#!/usr/bin/env bash
# Soft-warn on edits to Specflow-generated files.
#
# Reads a JSON event from stdin (Claude Code's PreToolUse payload), prints
# a stderr warning if the target is a managed file, then exits 0 — does
# NOT block. The point is to nudge users who attempt to hand-edit files
# that get regenerated by `specflow upgrade`, not to enforce.
set -euo pipefail

INPUT=$(cat || true)
if [ -z "$INPUT" ]; then
  exit 0
fi

# Extract the target file path. The PreToolUse JSON shape is
# { "tool_name": "Edit"|"Write", "tool_input": { "file_path": "..." } }.
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
if [ -z "$FILE" ]; then
  exit 0
fi

case "$FILE" in
  *.specflow/installed.lock|*/.specflow/installed.lock)
    cat >&2 <<'WARN'
warn: .specflow/installed.lock is generated by `specflow init` / `specflow
      upgrade`. Manual edits will be overwritten by the next upgrade. If
      you need to change the recorded harness or backend, re-run
      `specflow upgrade` instead.
WARN
    ;;
esac

exit 0
