#!/usr/bin/env python3
"""
handoff-to-copilot — Phase 3 of /speckit specify --copilot.

Commits and pushes the spec files, opens a draft PR from the linked
branch to main with a body listing spec URLs and implementation
instructions, then assigns GitHub Copilot via @copilot mention.

Prerequisite: the auto-chain (specify → clarify → plan → tasks → analyze)
has completed on the linked branch.

Usage:
    python3 .claude/skills/speckit/scripts/handoff-to-copilot.py \\
        --feature-dir specs/87-photo-grid-profile \\
        --issue-number 87 \\
        --branch 87-photo-grid-profile \\
        --title "Migrate Public Profile Grid to react-photo-album" \\
        [--dry-run]

Exit codes:
    0 — success
    1 — generic failure
    2 — feature dir missing required files (spec.md / plan.md / tasks.md)
    3 — git or gh failure
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

REPO = "miximodel/miximodel"
BRANCH_DEFAULT = "main"


def run(cmd: list, dry_run: bool, check=True) -> str:
    """Run a shell command; honor dry-run; return stdout."""
    if dry_run:
        print(f"[dry-run] {' '.join(cmd)}")
        return ""
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"Command failed: {' '.join(cmd)}\n{result.stderr}", file=sys.stderr)
        sys.exit(3)
    return result.stdout.strip()


def required_specs_exist(feature_dir: Path) -> None:
    """Fail if spec.md, plan.md, or tasks.md is missing."""
    for name in ("spec.md", "plan.md", "tasks.md"):
        if not (feature_dir / name).exists():
            print(f"Missing required spec file: {feature_dir / name}", file=sys.stderr)
            sys.exit(2)


def build_pr_body(feature_dir: Path, branch: str, issue_number: int) -> str:
    """Render the PR body with links to every spec artifact that exists."""
    base = f"../blob/{branch}/{feature_dir}"
    lines = [
        "<!-- Auto-generated by /speckit specify --copilot. Do not edit above this line. -->",
        "",
        f"Closes #{issue_number}",
        "",
        "## Specifications",
        "",
        "This PR must be implemented in strict accordance with the following",
        "specification files, located in this branch:",
        "",
    ]
    optional_files = [
        ("spec.md", "functional requirements"),
        ("plan.md", "technical plan and architecture"),
        ("tasks.md", "ordered task checklist"),
        ("research.md", "technical decisions"),
        ("data-model.md", "entities"),
        ("quickstart.md", "validation guide"),
    ]
    for name, desc in optional_files:
        if (feature_dir / name).exists():
            lines.append(f"- [{name}]({base}/{name}) — {desc}")
    contracts_dir = feature_dir / "contracts"
    if contracts_dir.exists() and contracts_dir.is_dir():
        lines.append(f"- [contracts/](../tree/{branch}/{feature_dir}/contracts) — API contracts")

    # Pull the backlog id from the feature dir (e.g. "specs/87-public-profile-..." → "87")
    backlog_hint = ""
    dir_name = feature_dir.name
    if dir_name and dir_name[:3].isdigit():
        backlog_hint = f" — matches `tasks/backlog/{dir_name[:3]}-*.md`"

    lines.extend([
        "",
        "## Implementation Instructions",
        "",
        "**You MUST follow the SpecKit Implement workflow documented at",
        f"[`.claude/commands/speckit.implement.md`](../blob/{branch}/.claude/commands/speckit.implement.md).**",
        "",
        "Rules:",
        "1. Read `spec.md`, `plan.md`, and `tasks.md` IN FULL before writing any code.",
        "2. Execute tasks from `tasks.md` IN ORDER. Check off each task as you complete it.",
        f"3. Follow every architecture rule in [`AGENTS.md`](../blob/{branch}/AGENTS.md) and",
        f"   [`.claude/skills/adonisjs-v7/SKILL.md`](../blob/{branch}/.claude/skills/adonisjs-v7/SKILL.md)",
        f"   for backend work, [`.claude/skills/react/SKILL.md`](../blob/{branch}/.claude/skills/react/SKILL.md) for frontend.",
        "4. Apply the Boy Scout Rule: fix warnings in files you touch.",
        "5. Never skip pre-commit hooks. Never use `--no-verify`.",
        f"6. **Close the backlog task locally before marking the PR ready for review.**{backlog_hint}",
        "   In the same branch, edit the linked `tasks/backlog/NNN-<slug>.md`: change the",
        "   `status:` frontmatter field from `todo` (or `in_progress`) to `done`. Then in",
        "   `tasks/backlog.md`, remove the task's `- [ ]` entry from its current priority",
        "   section and add a `- [x]` entry in the `## Done` section (preserve the one-line",
        "   description, append \"(delivered by GitHub Copilot via PR #<this PR number>)\" at the",
        "   end). Update the Summary table at the bottom: decrement the source priority's",
        "   count by 1, increment `Done` by 1, and increment `Done points` by the task's",
        "   complexity. Commit this as a separate commit titled",
        "   `chore(backlog): mark task NNN as done — merged via Copilot PR #<N>`. **Skipping",
        "   this step will cause the local Markdown backlog and GitHub Issues to diverge",
        "   after merge.**",
        "7. When all tasks in `tasks.md` are checked AND the backlog task is closed as",
        "   described in rule 6, mark this PR ready for review.",
        "",
        "/cc @copilot — please implement this following the custom agent `adonisjs`.",
    ])
    return "\n".join(lines)


def git_commit_and_push(feature_dir: Path, issue_number: int, branch: str, dry_run: bool):
    """Stage specs, commit, push the branch."""
    run(["git", "add", str(feature_dir)], dry_run)
    status = run(["git", "status", "--porcelain"], dry_run=False, check=False)
    if not dry_run and not status.strip():
        print("No changes to commit — was the auto-chain run on this branch?", file=sys.stderr)
        sys.exit(1)
    run(
        ["git", "commit", "-m", f"chore(spec): scaffold specs for issue #{issue_number}"],
        dry_run,
    )
    run(["git", "push", "-u", "origin", branch], dry_run)


def open_draft_pr(title: str, body: str, branch: str, dry_run: bool) -> str:
    """Open a draft PR targeting main. Return its URL."""
    if dry_run:
        print(f"[dry-run] would open draft PR: title='{title}' branch='{branch}'")
        print("---- PR body preview ----")
        print(body)
        print("---- end preview ----")
        return "https://example.com/pr-dry-run"
    url = run(
        [
            "gh", "pr", "create",
            "--repo", REPO,
            "--draft",
            "--base", BRANCH_DEFAULT,
            "--head", branch,
            "--title", f"[Copilot] {title}",
            "--body", body,
        ],
        dry_run=False,
    )
    return url


def assign_copilot(pr_url: str, dry_run: bool):
    """Add a comment mentioning @copilot to trigger the Coding Agent."""
    if dry_run:
        print(f"[dry-run] would post @copilot trigger comment on {pr_url}")
        return
    comment = (
        "@copilot please implement the tasks in the linked `tasks.md` "
        "following the SpecKit Implement workflow. Use the `adonisjs` "
        "custom agent for this repository."
    )
    run(
        ["gh", "pr", "comment", pr_url, "--body", comment],
        dry_run=False,
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--feature-dir", required=True, type=Path)
    parser.add_argument("--issue-number", required=True, type=int)
    parser.add_argument("--branch", required=True)
    parser.add_argument("--title", required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    required_specs_exist(args.feature_dir)
    body = build_pr_body(args.feature_dir, args.branch, args.issue_number)

    git_commit_and_push(args.feature_dir, args.issue_number, args.branch, args.dry_run)
    pr_url = open_draft_pr(args.title, body, args.branch, args.dry_run)
    assign_copilot(pr_url, args.dry_run)

    print(json.dumps({"pr_url": pr_url, "branch": args.branch}))


if __name__ == "__main__":
    main()
