import type { BacklogBackendStrategy } from "../backlog_backend_strategy.ts";

const EMPTY_STUB = `# backlog-config.yml — generated by \`specflow init --backlog cloud\`
# Fill in api_url + api_token + project_key before the PO can run any backlog command.
api_url: ""        # Specflow Cloud API base, e.g. https://your-deployment.convex.site
api_token: ""      # Specflow Cloud API token (sfc_…)
project_key: ""    # the project's short key, e.g. CLOUD
`;

export class CloudBacklogStrategy implements BacklogBackendStrategy {
  readonly key = "cloud" as const;
  readonly displayName = "Specflow Cloud (real-time API — requires a token)";

  // Cloud config is an API endpoint + token, not a Kanban URL, so there is no
  // URL auto-population — always render the empty stub for the user to fill.
  initConfigStub(): string {
    return EMPTY_STUB;
  }

  initConfigMessages(): readonly string[] {
    return [
      "↳ wrote .specflow/backlog-config.yml — fill in api_url + api_token + project_key before running /backlog",
      "  tip: create a Specflow Cloud project + API token, then paste the token (sfc_…) and project key here",
    ];
  }
}
