import type { BacklogBackendStrategy, StubContext } from "../backlog_backend_strategy.ts";

const EMPTY_STUB = `# backlog-config.yml — generated by \`specnaut init --backlog github\`
# Fill in repo + project_number before the PO can run any backlog command.
repo: ""              # e.g. myorg/myproject
project_number: ""    # GitHub Project V2 number
# project_node_id and status_field_id are cached on first run.
project_node_id: ""
status_field_id: ""
`;

function populatedStub(repo: string, projectNumber: number): string {
  return `# backlog-config.yml — generated by \`specnaut init --backlog github\`
repo: "${repo}"
project_number: "${projectNumber}"
# project_node_id and status_field_id are cached on first run.
project_node_id: ""
status_field_id: ""
`;
}

export class GithubBacklogStrategy implements BacklogBackendStrategy {
  readonly key = "github" as const;
  readonly displayName = "GitHub Issues + Project (requires gh CLI)";

  initConfigStub(ctx?: StubContext): string {
    const url = ctx?.url;
    const repo = ctx?.repo;
    if (url && url.kind === "github" && repo && repo.length > 0) {
      return populatedStub(repo, url.projectNumber);
    }
    return EMPTY_STUB;
  }

  initConfigMessages(ctx?: StubContext): readonly string[] {
    const populated = ctx?.url?.kind === "github" && ctx?.repo && ctx.repo.length > 0;
    if (populated) {
      return [
        `↳ wrote .specnaut/backlog-config.yml (${ctx!.repo} → project #${
          (ctx!.url as { kind: "github"; projectNumber: number }).projectNumber
        }) — ready to run /backlog`,
        "  tip: for a richer experience, enable the GitHub MCP connector via `/mcp` in Claude Code",
      ];
    }
    return [
      "↳ wrote .specnaut/backlog-config.yml — fill in repo + project_number before running /backlog",
      "  tip: for a richer experience, enable the GitHub MCP connector via `/mcp` in Claude Code",
    ];
  }
}
