import type { BacklogBackendStrategy } from "../backlog_backend_strategy.ts";

const CONFIG_STUB = `# backlog-config.yml — generated by \`specflow init --backlog github\`
# Fill in repo + project_number before the PO can run any backlog command.
repo: ""              # e.g. myorg/myproject
project_number: ""    # GitHub Project V2 number
# project_node_id and status_field_id are cached on first run.
project_node_id: ""
status_field_id: ""
`;

export class GithubBacklogStrategy implements BacklogBackendStrategy {
  readonly key = "github" as const;
  readonly displayName = "GitHub Issues + Project (requires gh CLI)";

  initConfigStub(): string {
    return CONFIG_STUB;
  }

  initConfigMessages(): readonly string[] {
    return [
      "↳ wrote .specflow/backlog-config.yml — fill in repo + project_number before running /backlog",
      "  tip: for a richer experience, enable the GitHub MCP connector via `/mcp` in Claude Code",
    ];
  }
}
