import type { BacklogBackendStrategy, StubContext } from "../backlog_backend_strategy.ts";

const EMPTY_STUB = `# backlog-config.yml — generated by \`specnaut init --backlog gitlab\`
# Fill in host + project_id before the PO can run any backlog command.
host: gitlab.com      # or your self-hosted instance, e.g. gitlab.example.com
project_id: ""        # GitLab project ID (numeric) or path "group/project"
# Status is tracked via scoped labels: Status::Backlog, Status::Ready,
# Status::"In progress", Status::"In review", Status::Done.
`;

function populatedStub(host: string, projectId: string): string {
  return `# backlog-config.yml — generated by \`specnaut init --backlog gitlab\`
host: ${host}
project_id: "${projectId}"
# Status is tracked via scoped labels: Status::Backlog, Status::Ready,
# Status::"In progress", Status::"In review", Status::Done.
`;
}

export class GitlabBacklogStrategy implements BacklogBackendStrategy {
  readonly key = "gitlab" as const;
  readonly displayName = "GitLab Issues + scoped Status labels (requires glab CLI)";

  initConfigStub(ctx?: StubContext): string {
    const url = ctx?.url;
    if (url && url.kind === "gitlab") {
      return populatedStub(url.host, url.projectPath);
    }
    return EMPTY_STUB;
  }

  initConfigMessages(ctx?: StubContext): readonly string[] {
    const url = ctx?.url;
    if (url && url.kind === "gitlab") {
      return [
        `↳ wrote .specflow/backlog-config.yml (${url.host}/${url.projectPath}) — ready to run /backlog`,
        "  prerequisite: install glab CLI (https://gitlab.com/gitlab-org/cli) and run `glab auth login`",
      ];
    }
    return [
      "↳ wrote .specflow/backlog-config.yml — fill in host + project_id before running /backlog",
      "  prerequisite: install glab CLI (https://gitlab.com/gitlab-org/cli) and run `glab auth login`",
    ];
  }
}
