import type { BacklogBackendStrategy } from "../backlog_backend_strategy.ts";

const CONFIG_STUB = `# backlog-config.yml — generated by \`specflow init --backlog gitlab\`
# Fill in host + project_id before the PO can run any backlog command.
host: gitlab.com      # or your self-hosted instance, e.g. gitlab.example.com
project_id: ""        # GitLab project ID (numeric) or path "group/project"
# Status is tracked via scoped labels: Status::Backlog, Status::Ready,
# Status::"In progress", Status::"In review", Status::Done.
`;

export class GitlabBacklogStrategy implements BacklogBackendStrategy {
  readonly key = "gitlab" as const;
  readonly displayName = "GitLab Issues + scoped Status labels (requires glab CLI)";

  initConfigStub(): string {
    return CONFIG_STUB;
  }

  initConfigMessages(): readonly string[] {
    return [
      "↳ wrote .specflow/backlog-config.yml — fill in host + project_id before running /backlog",
      "  prerequisite: install glab CLI (https://gitlab.com/gitlab-org/cli) and run `glab auth login`",
    ];
  }
}
