import { resolve } from "@std/path";
import { bold, dim, green, red, yellow } from "@std/fmt/colors";
import { InitProjectUseCase } from "../../application/init_project.ts";
import { findHarness } from "../harnesses.ts";
import { DEFAULT_HARNESS, type HarnessKey, pickHarness } from "../harness_picker.ts";
import { DEFAULT_BACKLOG_BACKEND, pickBacklogBackend } from "../backlog_picker.ts";
import type { BacklogBackend } from "../../domain/installed_lock.ts";
import { DenoFsWriter } from "../../infrastructure/deno_fs_writer.ts";
import { DenoGit } from "../../infrastructure/deno_git.ts";
import { FsLockStore } from "../../infrastructure/fs_lock_store.ts";
import { CORE_BUNDLE } from "../../templates_bundle.ts";

export type InitIntent = {
  kind: "init";
  projectName: string | null;
  here: boolean;
  noGit: boolean;
  ai: HarnessKey | null;
  backlog: BacklogBackend | null;
  force: boolean;
};

function resolveHarnessKey(explicit: HarnessKey | null): HarnessKey {
  if (explicit !== null) return explicit;
  if (!Deno.stdin.isTerminal()) return DEFAULT_HARNESS;
  return pickHarness({
    readLine: () => prompt("Choose [1-8]:"),
    log: (s) => console.log(s),
    errLog: (s) => console.error(red(s)),
  });
}

function resolveBacklogBackend(explicit: BacklogBackend | null): BacklogBackend {
  if (explicit !== null) return explicit;
  if (!Deno.stdin.isTerminal()) return DEFAULT_BACKLOG_BACKEND;
  return pickBacklogBackend({
    readLine: () => prompt("Choose [1-3]:"),
    log: (s) => console.log(s),
    errLog: (s) => console.error(red(s)),
  });
}

const GITHUB_CONFIG_STUB = `# backlog-config.yml — generated by \`specflow init --backlog github\`
# Fill in repo + project_number before the PO can run any backlog command.
repo: ""              # e.g. myorg/myproject
project_number: ""    # GitHub Project V2 number
# project_node_id and status_field_id are cached on first run.
project_node_id: ""
status_field_id: ""
`;

const GITLAB_CONFIG_STUB = `# backlog-config.yml — generated by \`specflow init --backlog gitlab\`
# Fill in host + project_id before the PO can run any backlog command.
host: gitlab.com      # or your self-hosted instance, e.g. gitlab.example.com
project_id: ""        # GitLab project ID (numeric) or path "group/project"
# Status is tracked via scoped labels: Status::Backlog, Status::Ready,
# Status::"In progress", Status::"In review", Status::Done.
`;

async function writeBacklogConfigStub(
  targetDir: string,
  backend: "github" | "gitlab",
): Promise<void> {
  const path = `${targetDir}/.specflow/backlog-config.yml`;
  try {
    await Deno.stat(path);
    return; // don't clobber an existing config
  } catch {
    // not present → write the stub
  }
  await Deno.mkdir(`${targetDir}/.specflow`, { recursive: true });
  const stub = backend === "github" ? GITHUB_CONFIG_STUB : GITLAB_CONFIG_STUB;
  await Deno.writeTextFile(path, stub);
  if (backend === "github") {
    console.log(
      dim(
        "↳ wrote .specflow/backlog-config.yml — fill in repo + project_number before running /backlog",
      ),
    );
    console.log(
      dim(
        "  tip: for a richer experience, enable the GitHub MCP connector via `/mcp` in Claude Code",
      ),
    );
  } else {
    console.log(
      dim(
        "↳ wrote .specflow/backlog-config.yml — fill in host + project_id before running /backlog",
      ),
    );
    console.log(
      dim(
        "  prerequisite: install glab CLI (https://gitlab.com/gitlab-org/cli) and run `glab auth login`",
      ),
    );
  }
}

export async function runInit(intent: InitIntent): Promise<number> {
  const cwd = Deno.cwd();

  let targetDir: string;
  if (intent.here) {
    targetDir = cwd;
  } else if (intent.projectName) {
    targetDir = resolve(cwd, intent.projectName);
  } else {
    console.error(red("error: `specflow init` requires a project name or --here"));
    return 2;
  }

  const aiKey = resolveHarnessKey(intent.ai);
  const harness = findHarness(aiKey);
  if (!harness) {
    console.error(red(`error: unknown harness '${aiKey}'`));
    return 2;
  }

  const backlogBackend = resolveBacklogBackend(intent.backlog);

  console.log(`Initializing into ${bold(targetDir)}`);

  const useCase = new InitProjectUseCase({
    writer: new DenoFsWriter(),
    git: new DenoGit(),
    lockStore: new FsLockStore(),
    harness,
    backlogBackend,
    core: CORE_BUNDLE,
    ensureDir: (path) => Deno.mkdir(path, { recursive: true }),
  });

  const result = await useCase.execute({
    targetDir,
    initGit: !intent.noGit,
    force: intent.force,
  });

  if (result.status === "conflicts") {
    console.error(
      red(`error: target already contains ${result.conflicts.length} specflow-managed file(s):`),
    );
    for (const c of result.conflicts) console.error(red(`  - ${c}`));
    console.error("\nTo proceed:");
    console.error(
      `  • Run ${bold("specflow init --here --force")} to re-initialise in place ` +
        "(existing files are backed up to *.specflow.bak).",
    );
    console.error(
      `  • Or run ${bold("specflow upgrade")} if this project was previously ` +
        "initialised by Specflow.",
    );
    return 3;
  }

  for (const w of result.warnings) console.error(yellow(`warn: ${w}`));
  for (const b of result.backups) console.log(dim(`↳ backed up ${b} → ${b}.specflow.bak`));
  const mergedSuffix = result.filesMerged.length > 0
    ? ` (+ merged: ${result.filesMerged.join(", ")})`
    : "";
  console.log(green(`✓ wrote ${result.filesWritten} files${mergedSuffix}`));

  if (backlogBackend === "github" || backlogBackend === "gitlab") {
    await writeBacklogConfigStub(targetDir, backlogBackend);
  }
  console.log("\nNext steps:");
  console.log(
    `  1. Open the project in ${harness.displayName}, then run ${
      bold("/specflow.constitution")
    } to scaffold your project's guiding principles`,
  );
  console.log(
    `  2. Edit ${bold("AGENTS.md")} and refine ${
      bold(".specflow/memory/constitution.md")
    } for your stack`,
  );
  console.log(
    `  3. Run ${bold('/specflow.specify "<feature description>"')} to scaffold your first feature`,
  );
  console.log(`  4. Use ${bold('/backlog add "<task title>"')} for follow-up work`);
  return 0;
}
