// Reads templates/manifest.json + templates/** and emits src/templates_bundle.ts.
// The generated module exports:
//   - TEMPLATES_VERSION: string
//   - CORE_BUNDLE: CoreBundle (from src/domain/core_bundle.ts)
//   - HARNESS_STATIC: Record<harnessKey, Record<destination, TemplateFile>>
// Runtime code reads nothing from disk.

import { relative } from "@std/path";

type CoreManifestEntry = {
  category: string;
  name: string;
  suffix?: string;
  source: string;
  executable?: boolean;
  /** When set, the entry only applies if this backend is selected. */
  backend?: "local" | "github" | "gitlab";
};

type HarnessStaticManifestEntry = {
  harness: string;
  destination: string;
  source: string;
  executable?: boolean;
};

type Manifest = {
  version: string;
  core: CoreManifestEntry[];
  harness_static: HarnessStaticManifestEntry[];
};

const ROOT = new URL("..", import.meta.url);
const TEMPLATES_DIR = new URL("templates/", ROOT);
const MANIFEST_PATH = new URL("templates/manifest.json", ROOT);
const OUTPUT_PATH = new URL("src/templates_bundle.ts", ROOT);

async function readManifest(): Promise<Manifest> {
  return JSON.parse(await Deno.readTextFile(MANIFEST_PATH)) as Manifest;
}

async function assertAllSourcesPresent(m: Manifest): Promise<void> {
  const missing: string[] = [];
  const check = async (source: string) => {
    const abs = new URL(source, TEMPLATES_DIR);
    try {
      const s = await Deno.stat(abs);
      if (!s.isFile) missing.push(source);
    } catch {
      missing.push(source);
    }
  };
  for (const e of m.core) await check(e.source);
  for (const e of m.harness_static) await check(e.source);
  if (missing.length > 0) {
    throw new Error(`Missing template sources:\n  - ${missing.join("\n  - ")}`);
  }
}

function escapeTemplateLiteral(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

async function buildCoreEntries(m: Manifest): Promise<string[]> {
  const lines: string[] = [];
  for (const entry of m.core) {
    const abs = new URL(entry.source, TEMPLATES_DIR);
    const content = await Deno.readTextFile(abs);
    const suffix = entry.suffix === undefined ? "null" : JSON.stringify(entry.suffix);
    const backend = entry.backend === undefined ? "null" : JSON.stringify(entry.backend);
    lines.push(
      `  {\n` +
        `    category: ${JSON.stringify(entry.category)},\n` +
        `    name: ${JSON.stringify(entry.name)},\n` +
        `    suffix: ${suffix},\n` +
        `    content: \`${escapeTemplateLiteral(content)}\`,\n` +
        `    executable: ${entry.executable === true},\n` +
        `    backend: ${backend},\n` +
        `  }`,
    );
  }
  return lines;
}

async function buildHarnessStatic(m: Manifest): Promise<string> {
  const byHarness: Record<
    string,
    Array<{ destination: string; content: string; executable: boolean }>
  > = {};
  for (const e of m.harness_static) {
    const abs = new URL(e.source, TEMPLATES_DIR);
    const content = await Deno.readTextFile(abs);
    byHarness[e.harness] ??= [];
    byHarness[e.harness].push({
      destination: e.destination,
      content,
      executable: e.executable === true,
    });
  }
  const outer: string[] = [];
  for (const harness of Object.keys(byHarness).sort()) {
    const inner = byHarness[harness].map((f) =>
      `    ${JSON.stringify(f.destination)}: {\n` +
      `      content: \`${escapeTemplateLiteral(f.content)}\`,\n` +
      `      executable: ${f.executable},\n` +
      `    }`
    ).join(",\n");
    outer.push(`  ${JSON.stringify(harness)}: {\n${inner},\n  }`);
  }
  return outer.join(",\n");
}

async function main() {
  const manifest = await readManifest();
  await assertAllSourcesPresent(manifest);
  const core = await buildCoreEntries(manifest);
  const staticBlock = await buildHarnessStatic(manifest);

  const src = `// THIS FILE IS GENERATED BY scripts/bundle-templates.ts — DO NOT EDIT BY HAND.
import type { CoreBundle } from "./domain/core_bundle.ts";
import type { TemplateFile } from "./domain/template.ts";

export const TEMPLATES_VERSION = ${JSON.stringify(manifest.version)};

export const CORE_BUNDLE: CoreBundle = [
${core.join(",\n")},
];

export const HARNESS_STATIC: Record<string, Record<string, TemplateFile>> = {
${staticBlock},
};
`;
  await Deno.writeTextFile(OUTPUT_PATH, src);
  console.log(
    `Bundled ${manifest.core.length} core entries + ${manifest.harness_static.length} harness-specific → ${
      relative(Deno.cwd(), OUTPUT_PATH.pathname)
    }`,
  );
}

if (import.meta.main) await main();
