// Reads templates/manifest.json + templates/** and emits src/templates_bundle.ts.
// The generated module holds every template file content as a string, indexed by
// destination path. Runtime code reads nothing from disk.

import { relative } from "@std/path";

type ManifestEntry = { source: string; destination: string; executable?: boolean };
type Manifest = { version: string; files: ManifestEntry[] };

const ROOT = new URL("..", import.meta.url);
const TEMPLATES_DIR = new URL("templates/", ROOT);
const MANIFEST_PATH = new URL("templates/manifest.json", ROOT);
const OUTPUT_PATH = new URL("src/templates_bundle.ts", ROOT);

async function readManifest(): Promise<Manifest> {
  const raw = await Deno.readTextFile(MANIFEST_PATH);
  return JSON.parse(raw) as Manifest;
}

async function assertAllSourcesPresent(manifest: Manifest): Promise<void> {
  const missing: string[] = [];
  for (const entry of manifest.files) {
    const abs = new URL(entry.source, TEMPLATES_DIR);
    try {
      const stat = await Deno.stat(abs);
      if (!stat.isFile) missing.push(entry.source);
    } catch {
      missing.push(entry.source);
    }
  }
  if (missing.length > 0) {
    throw new Error(`Missing template sources:\n  - ${missing.join("\n  - ")}`);
  }
}

async function buildBundle(manifest: Manifest): Promise<string> {
  const entries: string[] = [];
  for (const entry of manifest.files) {
    const abs = new URL(entry.source, TEMPLATES_DIR);
    const content = await Deno.readTextFile(abs);
    const escaped = content
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$/g, "\\$");
    entries.push(
      `  ${JSON.stringify(entry.destination)}: {\n` +
        `    content: \`${escaped}\`,\n` +
        `    executable: ${entry.executable === true},\n` +
        `  }`,
    );
  }
  return `// THIS FILE IS GENERATED BY scripts/bundle-templates.ts — DO NOT EDIT BY HAND.
export type TemplateFile = {
  content: string;
  executable: boolean;
};

export const TEMPLATES_VERSION = ${JSON.stringify(manifest.version)};

export const TEMPLATES: Record<string, TemplateFile> = {
${entries.join(",\n")}
};
`;
}

async function main() {
  const manifest = await readManifest();
  await assertAllSourcesPresent(manifest);
  const bundle = await buildBundle(manifest);
  await Deno.writeTextFile(OUTPUT_PATH, bundle);
  console.log(
    `Bundled ${manifest.files.length} template(s) → ${relative(Deno.cwd(), OUTPUT_PATH.pathname)}`,
  );
}

if (import.meta.main) {
  await main();
}
