// Installs `hooks/pre-commit` into the repository's hooks directory. Run via
// `deno task setup`. Idempotent.
//
// What gets installed is a SHIM, not a symlink to the hook. The shim asks git
// for the worktree root at run time and execs `hooks/pre-commit` from there.
//
// The previous shape wrote an absolute symlink, whose text was the path the
// checkout occupied at install time. Move or rename the directory and the link
// dangles — and git `stat()`s THROUGH a symlink, so a dangling hook is
// indistinguishable from no hook at all. Commits keep succeeding with none of
// the four gates run, and nothing anywhere says so. That is not hypothetical:
// in a maintainer checkout the link pointed into a directory renamed away, and
// the hook was inert for close to four months (#591).
//
// A shim resolves at run time, so it survives any move of the checkout without
// being reinstalled.

import { resolve } from "@std/path";

const ROOT = new URL("..", import.meta.url).pathname;

/**
 * How the installer recognises a hook it wrote. A shim is a regular file, so
 * "is this ours?" is a content question — and it has to be answerable, because
 * refusing to touch a hook we installed ourselves is the second half of #591.
 */
export const SHIM_MARKER = "specnaut-managed pre-commit shim";

/**
 * The shim FAILS when it cannot find the hook. A shim that exec'd nothing and
 * exited 0 would reproduce the defect it exists to fix, one layer in: the
 * commit would pass because no check ran, which is the reading this whole
 * ticket is about.
 */
export function shimContent(): string {
  return `#!/usr/bin/env bash
# ${SHIM_MARKER} — installed by \`deno task setup\`.
#
# Resolves the worktree at RUN time and runs the tracked hook from it, so the
# install survives a move or rename of the checkout. Do not edit this file;
# edit hooks/pre-commit, which is what actually runs.
set -euo pipefail

root=$(git rev-parse --show-toplevel)
hook="$root/hooks/pre-commit"

if [ ! -x "$hook" ]; then
  echo "pre-commit: $hook is missing or not executable" >&2
  echo "  The shim found the worktree but no hook to run." >&2
  echo "  This is a broken install, not a pass — run \\\`deno task setup\\\`." >&2
  exit 1
fi

exec "$hook"
`;
}

async function lstatOrNull(path: string): Promise<Deno.FileInfo | null> {
  try {
    return await Deno.lstat(path);
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) return null;
    throw e;
  }
}

/** `mode` is null on platforms that do not report it; treat that as executable. */
function isExecutable(info: Deno.FileInfo): boolean {
  return info.mode === null || (info.mode & 0o111) !== 0;
}

async function resolves(path: string): Promise<boolean> {
  try {
    await Deno.stat(path);
    return true;
  } catch {
    return false;
  }
}

/** What is sitting at the hook target, and whether we may replace it. */
export type HookState =
  | { kind: "absent" }
  | { kind: "ours-shim" }
  | { kind: "legacy-symlink"; link: string; dangling: boolean }
  | { kind: "foreign"; detail: string };

/**
 * Classify the hook target.
 *
 * The load-bearing case is `legacy-symlink` with `dangling: true`. The old code
 * read the link, saw text that no longer matched its own SOURCE, and fell
 * through to "exists and is not our symlink" — treating a link that points at
 * nothing exactly like a hand-written hook that must not be clobbered. A
 * dangling link can only ever be stale: nothing useful points at a file that
 * does not exist.
 */
export async function classifyHook(target: string, source: string): Promise<HookState> {
  const info = await lstatOrNull(target);
  if (info === null) return { kind: "absent" };

  if (info.isSymlink) {
    const link = await Deno.readLink(target);
    const dangling = !(await resolves(target));
    if (dangling) return { kind: "legacy-symlink", link, dangling: true };
    if (link === source) return { kind: "legacy-symlink", link, dangling: false };
    return { kind: "foreign", detail: `a symlink to ${link}` };
  }

  const body = await Deno.readTextFile(target).catch(() => "");
  if (body.includes(SHIM_MARKER)) return { kind: "ours-shim" };
  return { kind: "foreign", detail: "a regular file this script did not write" };
}

// Resolve the real hooks directory via `git rev-parse --git-path hooks`.
// We can't hardcode `<repo>/.git/hooks` because that path is wrong when the
// repo is checked out as a git submodule — there `.git` is a *gitdir file*
// (`gitdir: ../../.git/modules/<name>`) pointing at the parent repo's
// `.git/modules/<name>/`, and the real hooks live there (#335). Letting
// git answer keeps the script correct in both layouts.
export async function resolveHooksDir(cwd: string): Promise<string> {
  const out = await new Deno.Command("git", {
    args: ["rev-parse", "--git-path", "hooks"],
    cwd,
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!out.success) {
    throw new Error(
      `error: not a git repository (\`git rev-parse\` failed in ${cwd}): ${
        new TextDecoder().decode(out.stderr).trim()
      }`,
    );
  }
  return resolve(cwd, new TextDecoder().decode(out.stdout).trim());
}

export type InstallResult = {
  ok: boolean;
  /** Exit code `main()` should use. */
  code: number;
  lines: string[];
};

/**
 * Install, upgrade or repair the pre-commit hook for the checkout at
 * `repoRoot`. Never assumes its own success: the last thing it does is check
 * that the thing it just wrote can actually reach a runnable hook.
 */
export async function installPreCommitHook(repoRoot: string): Promise<InstallResult> {
  const source = resolve(repoRoot, "hooks/pre-commit");
  const lines: string[] = [];

  let hooksDir: string;
  try {
    hooksDir = await resolveHooksDir(repoRoot);
  } catch (e) {
    return { ok: false, code: 1, lines: [e instanceof Error ? e.message : String(e)] };
  }
  const target = resolve(hooksDir, "pre-commit");
  await Deno.mkdir(hooksDir, { recursive: true });

  const state = await classifyHook(target, source);

  if (state.kind === "foreign") {
    return {
      ok: false,
      code: 2,
      lines: [
        `error: ${target} exists and was not installed by this script ` +
        `(${state.detail}). Back it up and re-run.`,
      ],
    };
  }

  if (state.kind === "legacy-symlink") {
    lines.push(
      state.dangling
        ? `  replacing a dangling symlink → ${state.link} (the target does not exist)`
        : `  replacing the old absolute symlink → ${state.link}`,
    );
  }

  if (state.kind !== "ours-shim") {
    // `remove` first: writing over a symlink follows it and would clobber the
    // tracked hook itself.
    if (state.kind === "legacy-symlink") await Deno.remove(target);
    await Deno.writeTextFile(target, shimContent());
    await Deno.chmod(target, 0o755);
    lines.push(`✓ installed pre-commit shim at ${target}`);
  } else {
    lines.push("✓ pre-commit shim already installed");
  }

  // Report the ACTUAL state, not the fact that we just wrote a file. An
  // installed-but-unrunnable hook is the exact condition #591 is about, and a
  // `✓` over it would be this script telling the same lie in a new shape.
  const problems: string[] = [];
  const installed = await lstatOrNull(target);
  if (installed === null) {
    problems.push(`${target} is not there after writing it`);
  } else if (!isExecutable(installed)) {
    problems.push(`${target} is not executable`);
  }
  if (!(await resolves(source))) {
    problems.push(`the hook it resolves to is missing: ${source}`);
  } else {
    const hook = await lstatOrNull(source);
    if (hook && !isExecutable(hook)) {
      problems.push(`the hook it resolves to is not executable: ${source}`);
    }
  }
  if (problems.length > 0) {
    return {
      ok: false,
      code: 3,
      lines: [...lines, ...problems.map((p) => `error: ${p}`)],
    };
  }

  lines.push(`  it runs ${source} via \`git rev-parse --show-toplevel\`, so a`);
  lines.push("  move of this checkout does not need another `deno task setup`");
  return { ok: true, code: 0, lines };
}

async function main() {
  const result = await installPreCommitHook(ROOT);
  for (const line of result.lines) {
    (result.ok ? console.log : console.error)(line);
  }
  if (!result.ok) Deno.exit(result.code);
}

if (import.meta.main) await main();
