#!/usr/bin/env bash
# Sync Specnaut → specnaut/specnaut-plugins fork (of openai/plugins).
#
# Triggered from .github/workflows/release.yml on every `v*` tag push,
# after the binary build + Homebrew tap bump. Mirrors the upstream
# pattern from obra/superpowers (scripts/sync-to-codex-plugin.sh,
# MIT-licensed) — deterministic rsync into a fork, then `gh pr create`
# against that fork's main. A human (Kevin) later merges that fork
# into the upstream openai/plugins marketplace.
#
# Required environment:
#   GH_TOKEN     — fine-grained PAT with Contents:write + Pull
#                  requests:write on specnaut/specnaut-plugins.
#                  Set via the CODEX_SYNC_TOKEN repo secret in
#                  release.yml (parallel to HOMEBREW_TAP_TOKEN).
#
# Optional environment:
#   SPECNAUT_VERSION — defaults to deno.json `version`. CI passes the
#                      tag-derived version explicitly.
#   DRY_RUN          — set to any non-empty value to print actions
#                      without pushing or opening a PR.
#
# Exit codes:
#   0   success (or "no changes — sync skipped" — the script bails
#       early if rsync produces an empty diff in the destination)
#   2   missing GH_TOKEN — emit ::warning:: and exit 0 in release.yml
#       (mirrors the HOMEBREW_TAP_TOKEN-missing pattern)
#   1   unexpected error
set -euo pipefail

# Shared helpers — token check, mktemp workdir, git bot identity,
# idempotent PR creation. See scripts/lib/sync-helpers.sh for the
# sync-script convention.
# shellcheck source=./lib/sync-helpers.sh
. "$(dirname "$0")/lib/sync-helpers.sh"

# Configuration — change FORK / DEST_REL if the marketplace topology shifts.
FORK="specnaut/specnaut-plugins"
UPSTREAM="openai/plugins"
DEST_REL="plugins/specnaut"
BRANCH_PREFIX="specnaut-sync"

# Resolve the version to ship.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="${SPECNAUT_VERSION:-$(jq -r '.version' "$REPO_ROOT/deno.json")}"

require_gh_token "CODEX_SYNC_TOKEN"

echo "specnaut → codex plugin sync (v$VERSION)"
echo "  fork:     $FORK"
echo "  dest:     $DEST_REL"
echo "  upstream: $UPSTREAM"

WORK_DIR="$(mktemp_workdir specnaut-codex-sync)"

if [ -n "${DRY_RUN:-}" ]; then
  echo "DRY_RUN: would clone $FORK into $WORK_DIR/fork"
  CLONE_TARGET="$WORK_DIR/fork"
  mkdir -p "$CLONE_TARGET/$DEST_REL"
  ( cd "$CLONE_TARGET" && git init -q )
else
  echo "Cloning $FORK..."
  gh repo clone "$FORK" "$WORK_DIR/fork" -- --depth 1
  CLONE_TARGET="$WORK_DIR/fork"
fi

cd "$CLONE_TARGET"

git_bot_identity
wire_gh_token_to_remote

# rsync EXCLUDES — what NOT to ship into the Codex marketplace.
# Inspired by superpowers' EXCLUDES array. We ship:
#   - .codex-plugin/plugin.json
#   - assets/                  (icons referenced by the manifest)
#   - plugin/skills/           (the bundled skill library)
# We DON'T ship:
#   - .claude-plugin/          (Claude Code-specific)
#   - .cursor-plugin/          (when it lands — Cursor-specific)
#   - .opencode/               (OpenCode-specific)
#   - .git/, .github/, docs/, tests/, src/, scripts/, etc.
EXCLUDES=(
  --exclude='/.git/'
  --exclude='/.github/'
  --exclude='/.claude-plugin/'
  --exclude='/.cursor-plugin/'
  --exclude='/.opencode/'
  --exclude='/.specnaut/'
  --exclude='/docs/'
  --exclude='/tests/'
  --exclude='/src/'
  --exclude='/scripts/'
  --exclude='/templates/'
  --exclude='/dist/'
  --exclude='/.claude/'
  --exclude='/.cursor/'
  --exclude='/.codex/'
  --exclude='/.windsurf/'
  --exclude='/.agents/'
  --exclude='/.opencode/'
  --exclude='/.gitignore'
  --exclude='/deno.json'
  --exclude='/deno.lock'
  --exclude='/install.sh'
  --exclude='/AGENTS.md'
  --exclude='/CLAUDE.md'
  --exclude='/CHANGELOG.md'
  --exclude='/CONTRIBUTING.md'
  --exclude='/SECURITY.md'
  --exclude='/CODE_OF_CONDUCT.md'
  --exclude='/LICENSE'
  --exclude='/README.md'
  --exclude='/RELEASE-NOTES.md'
  --exclude='/package.json'
  --exclude='/Cargo.toml'
  --exclude='**/.DS_Store'
  --exclude='**/node_modules/'
  --exclude='**/__pycache__/'
)

# Sync source → fork/plugins/specnaut/.
mkdir -p "$CLONE_TARGET/$DEST_REL"
echo "Syncing $REPO_ROOT → $CLONE_TARGET/$DEST_REL ..."
rsync -av --delete "${EXCLUDES[@]}" \
  "$REPO_ROOT/" "$CLONE_TARGET/$DEST_REL/"

# Detect "no changes" early — superpowers' pattern, avoids opening
# empty PRs on no-op releases.
if [ -z "$(git status --porcelain)" ]; then
  echo "No changes to sync — $FORK is already in sync with v$VERSION."
  exit 0
fi

BRANCH="$BRANCH_PREFIX/v$VERSION"
TITLE="chore(specnaut): sync to v$VERSION"
BODY=$(cat <<EOF
Automated sync from \`specnaut/specnaut-cli\` v$VERSION.

This PR mirrors the latest Specnaut plugin content into
\`plugins/specnaut/\` of this marketplace fork. A human reviewer
should rebase + merge this PR into upstream \`$UPSTREAM\` after
sanity-checking the diff.

Generated by \`scripts/sync-to-codex-plugin.sh\` in
[specnaut/specnaut-cli](https://github.com/specnaut/specnaut-cli).
EOF
)

if [ -n "${DRY_RUN:-}" ]; then
  echo "DRY_RUN: would create branch $BRANCH"
  echo "DRY_RUN: would commit + push to $FORK"
  echo "DRY_RUN: would open PR with title: $TITLE"
  exit 0
fi

git checkout -b "$BRANCH"
git add -A
git commit -m "$TITLE"
git push -u origin "$BRANCH"

create_pr_idempotent "$FORK" "$BRANCH" "$TITLE" "$BODY"

echo "✓ Specnaut synced to $FORK:$BRANCH (v$VERSION)"
