#!/usr/bin/env bash
# Sync Specflow → mkrlabs/specflow-marketplace catalog.
#
# Triggered from .github/workflows/release.yml on every `v*` tag push,
# after the binary build + Homebrew tap + Codex marketplace sync. The
# marketplace repo's `.claude-plugin/marketplace.json` catalog gets a
# version bump (and any other metadata refresh) on every release.
#
# The marketplace serves BOTH Claude Code and Copilot CLI users via
# the shared `.claude-plugin/marketplace.json` format:
#
#   - Claude Code: `/plugin marketplace add mkrlabs/specflow-marketplace`
#                  + `/plugin install specflow@specflow-marketplace`
#   - Copilot CLI: `copilot plugin marketplace add mkrlabs/specflow-marketplace`
#                  + `copilot plugin install specflow@specflow-marketplace`
#
# (Closes Epic #270 / B5 #281 — Copilot CLI marketplace entry.)
#
# Required environment:
#   GH_TOKEN — fine-grained PAT with Contents:write + Pull
#              requests:write on mkrlabs/specflow-marketplace.
#              Set via the MARKETPLACE_SYNC_TOKEN repo secret in
#              release.yml.
#
# Optional environment:
#   SPECFLOW_VERSION — defaults to deno.json `version`. CI passes the
#                      tag-derived version explicitly.
#   DRY_RUN          — set to any non-empty value to print actions
#                      without pushing or opening a PR.
#
# Exit codes:
#   0   success (or "no changes — sync skipped" if the catalog is
#       already in sync with the current version)
#   2   missing GH_TOKEN — emit ::warning:: and exit 0 in release.yml
#       (mirrors the HOMEBREW_TAP_TOKEN / CODEX_SYNC_TOKEN pattern)
#   1   unexpected error
set -euo pipefail

# Configuration.
MARKETPLACE="mkrlabs/specflow-marketplace"
BRANCH_PREFIX="specflow-sync"

# Resolve the version to ship.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="${SPECFLOW_VERSION:-$(jq -r '.version' "$REPO_ROOT/deno.json")}"

if [ -z "${GH_TOKEN:-}" ] && [ -z "${DRY_RUN:-}" ]; then
  echo "::warning::MARKETPLACE_SYNC_TOKEN (GH_TOKEN) not set — skipping marketplace sync" >&2
  exit 2
fi

echo "specflow → marketplace sync (v$VERSION)"
echo "  marketplace: $MARKETPLACE"

# Working dir — never commit to the source tree.
WORK_DIR="$(mktemp -d -t specflow-marketplace-sync-XXXXXX)"
trap 'rm -rf "$WORK_DIR"' EXIT

if [ -n "${DRY_RUN:-}" ]; then
  echo "DRY_RUN: would clone $MARKETPLACE into $WORK_DIR/marketplace"
  CLONE_TARGET="$WORK_DIR/marketplace"
  mkdir -p "$CLONE_TARGET/.claude-plugin"
  ( cd "$CLONE_TARGET" && git init -q )
  # Seed with a minimal marketplace.json so the update step has
  # something to patch in DRY_RUN mode.
  cat > "$CLONE_TARGET/.claude-plugin/marketplace.json" <<MARKETPLACE_JSON
{
  "plugins": [
    {
      "name": "specflow",
      "version": "0.0.0",
      "description": "Spec-driven workflow",
      "repository": "https://github.com/mkrlabs/specflow"
    }
  ]
}
MARKETPLACE_JSON
else
  echo "Cloning $MARKETPLACE..."
  gh repo clone "$MARKETPLACE" "$WORK_DIR/marketplace" -- --depth 1
  CLONE_TARGET="$WORK_DIR/marketplace"
fi

cd "$CLONE_TARGET"

# Git identity for the commit.
git config user.email "specflow-bot@mkrlabs.dev"
git config user.name "Specflow Marketplace Sync Bot"

# Update the specflow entry's version in the catalog. The catalog
# JSON shape is canonical Claude Code marketplace format
# (.claude-plugin/marketplace.json): a top-level object with a
# `plugins` array. Each plugin entry has at minimum `name`, `version`,
# `description`, `repository`. We patch only the `version` field of
# the entry whose `name == "specflow"`; everything else is preserved.
CATALOG=".claude-plugin/marketplace.json"
if [ ! -f "$CATALOG" ]; then
  echo "::error::$CATALOG not found in $MARKETPLACE — initialize the marketplace catalog first (see issue #281 follow-up tasks)" >&2
  exit 1
fi

jq --arg v "$VERSION" \
  '(.plugins[] | select(.name == "specflow") | .version) = $v' \
  "$CATALOG" > "$CATALOG.tmp"
mv "$CATALOG.tmp" "$CATALOG"

# Detect "no changes" early.
if [ -z "$(git status --porcelain)" ]; then
  echo "No changes to sync — $MARKETPLACE is already at v$VERSION."
  exit 0
fi

BRANCH="$BRANCH_PREFIX/v$VERSION"
TITLE="chore: bump specflow to v$VERSION"
BODY=$(cat <<EOF
Automated marketplace catalog bump from \`mkrlabs/specflow\` v$VERSION.

Patches \`.claude-plugin/marketplace.json\` so users on Claude Code
and Copilot CLI installing via the marketplace get the latest version
metadata. A maintainer rebases and merges this PR (or auto-merges
via branch protection rules).

Generated by \`scripts/sync-to-marketplace.sh\` in
[mkrlabs/specflow](https://github.com/mkrlabs/specflow).
EOF
)

if [ -n "${DRY_RUN:-}" ]; then
  echo "DRY_RUN: would create branch $BRANCH"
  echo "DRY_RUN: would commit + push to $MARKETPLACE"
  echo "DRY_RUN: would open PR with title: $TITLE"
  echo ""
  echo "Catalog diff preview:"
  git diff "$CATALOG"
  exit 0
fi

git checkout -b "$BRANCH"
git add "$CATALOG"
git commit -m "$TITLE"
git push -u origin "$BRANCH"

if ! gh pr create --repo "$MARKETPLACE" --base main --head "$BRANCH" \
  --title "$TITLE" --body "$BODY" 2>/dev/null; then
  echo "PR already exists for $BRANCH; skipping create."
fi

echo "✓ Specflow synced to $MARKETPLACE:$BRANCH (v$VERSION)"
