#!/usr/bin/env bash
# Sync Specnaut → specnaut/specnaut-marketplace catalog.
#
# Triggered from .github/workflows/release.yml on every `v*` tag push,
# after the binary build + Homebrew tap + Codex marketplace sync. The
# marketplace repo's `.claude-plugin/marketplace.json` catalog gets a
# version bump (and any other metadata refresh) on every release.
#
# The marketplace serves BOTH Claude Code and Copilot CLI users via
# the shared `.claude-plugin/marketplace.json` format:
#
#   - Claude Code: `/plugin marketplace add specnaut/specnaut-marketplace`
#                  + `/plugin install specnaut@specnaut-marketplace`
#   - Copilot CLI: `copilot plugin marketplace add specnaut/specnaut-marketplace`
#                  + `copilot plugin install specnaut@specnaut-marketplace`
#
# (Closes Epic #270 / B5 #281 — Copilot CLI marketplace entry.)
#
# Required environment:
#   GH_TOKEN — fine-grained PAT with Contents:write + Pull
#              requests:write on specnaut/specnaut-marketplace.
#              Set via the MARKETPLACE_SYNC_TOKEN repo secret in
#              release.yml.
#
# Optional environment:
#   SPECNAUT_VERSION — defaults to deno.json `version`. CI passes the
#                      tag-derived version explicitly.
#   DRY_RUN          — set to any non-empty value to print actions
#                      without pushing or opening a PR.
#
# Exit codes:
#   0   success (or "no changes — sync skipped" if the catalog is
#       already in sync with the current version)
#   2   missing GH_TOKEN — emit ::warning:: and exit 0 in release.yml
#       (mirrors the HOMEBREW_TAP_TOKEN / CODEX_SYNC_TOKEN pattern)
#   1   unexpected error
set -euo pipefail

# Shared helpers — token check, mktemp workdir, git bot identity,
# idempotent PR creation. See scripts/lib/sync-helpers.sh.
# shellcheck source=./lib/sync-helpers.sh
. "$(dirname "$0")/lib/sync-helpers.sh"

# Configuration.
MARKETPLACE="specnaut/specnaut-marketplace"
BRANCH_PREFIX="specnaut-sync"

# Resolve the version to ship.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="${SPECNAUT_VERSION:-$(jq -r '.version' "$REPO_ROOT/deno.json")}"

require_gh_token "MARKETPLACE_SYNC_TOKEN"

echo "specnaut → marketplace sync (v$VERSION)"
echo "  marketplace: $MARKETPLACE"

WORK_DIR="$(mktemp_workdir specnaut-marketplace-sync)"

if [ -n "${DRY_RUN:-}" ]; then
  echo "DRY_RUN: would clone $MARKETPLACE into $WORK_DIR/marketplace"
  CLONE_TARGET="$WORK_DIR/marketplace"
  mkdir -p "$CLONE_TARGET/.claude-plugin"
  ( cd "$CLONE_TARGET" && git init -q )
  # Seed with a minimal marketplace.json so the update step has
  # something to patch in DRY_RUN mode.
  cat > "$CLONE_TARGET/.claude-plugin/marketplace.json" <<MARKETPLACE_JSON
{
  "plugins": [
    {
      "name": "specnaut",
      "version": "0.0.0",
      "description": "Spec-driven workflow",
      "repository": "https://github.com/specnaut/specnaut-cli"
    }
  ]
}
MARKETPLACE_JSON
else
  echo "Cloning $MARKETPLACE..."
  gh repo clone "$MARKETPLACE" "$WORK_DIR/marketplace" -- --depth 1
  CLONE_TARGET="$WORK_DIR/marketplace"
fi

cd "$CLONE_TARGET"

git_bot_identity
wire_gh_token_to_remote

# Update the specnaut entry's version in the catalog. The catalog
# JSON shape is canonical Claude Code marketplace format
# (.claude-plugin/marketplace.json): a top-level object with a
# `plugins` array. Each plugin entry has at minimum `name`, `version`,
# `description`, `repository`. We patch only the `version` field of
# the entry whose `name == "specnaut"`; everything else is preserved.
CATALOG=".claude-plugin/marketplace.json"
if [ ! -f "$CATALOG" ]; then
  echo "::error::$CATALOG not found in $MARKETPLACE — initialize the marketplace catalog first (see issue #281 follow-up tasks)" >&2
  exit 1
fi

jq --arg v "$VERSION" \
  '(.plugins[] | select(.name == "specnaut") | .version) = $v' \
  "$CATALOG" > "$CATALOG.tmp"
mv "$CATALOG.tmp" "$CATALOG"

# Detect "no changes" early.
if [ -z "$(git status --porcelain)" ]; then
  echo "No changes to sync — $MARKETPLACE is already at v$VERSION."
  exit 0
fi

BRANCH="$BRANCH_PREFIX/v$VERSION"
TITLE="chore: bump specnaut to v$VERSION"
BODY=$(cat <<EOF
Automated marketplace catalog bump from \`specnaut/specnaut-cli\` v$VERSION.

Patches \`.claude-plugin/marketplace.json\` so users on Claude Code
and Copilot CLI installing via the marketplace get the latest version
metadata. A maintainer rebases and merges this PR (or auto-merges
via branch protection rules).

Generated by \`scripts/sync-to-marketplace.sh\` in
[specnaut/specnaut-cli](https://github.com/specnaut/specnaut-cli).
EOF
)

if [ -n "${DRY_RUN:-}" ]; then
  echo "DRY_RUN: would create branch $BRANCH"
  echo "DRY_RUN: would commit + push to $MARKETPLACE"
  echo "DRY_RUN: would open PR with title: $TITLE"
  echo ""
  echo "Catalog diff preview:"
  git diff "$CATALOG"
  exit 0
fi

git checkout -b "$BRANCH"
git add "$CATALOG"
git commit -m "$TITLE"
git push -u origin "$BRANCH"

create_pr_idempotent "$MARKETPLACE" "$BRANCH" "$TITLE" "$BODY"

echo "✓ Specnaut synced to $MARKETPLACE:$BRANCH (v$VERSION)"
