// THIS FILE IS GENERATED BY scripts/bundle-templates.ts — DO NOT EDIT BY HAND.
export type TemplateFile = {
  content: string;
  executable: boolean;
};

export const TEMPLATES_VERSION = "0.1.0";

export const TEMPLATES: Record<string, TemplateFile> = {};
